DO $$
DECLARE
    v_host text;
BEGIN
    SELECT inet_server_addr()::text
    INTO v_host;

    IF v_host <> '10.141.44.18/32' THEN
        RAISE EXCEPTION 'Refusing to run: connected to % instead of the approved server', v_host;
    END IF;
END
$$;

truncate table appreg.application_codes cascade;
truncate table appreg.application_lists cascade;
truncate table appreg.application_list_entries cascade;
truncate table appreg.application_register cascade;
truncate table appreg.app_list_entry_fee_id cascade;
truncate table appreg.app_list_entry_fee_status cascade;
truncate table appreg.app_list_entry_official cascade;
truncate table appreg.app_list_entry_resolutions cascade;
truncate table appreg.criminal_justice_area cascade;
truncate table appreg.fee cascade;
truncate table appreg.name_address cascade;
truncate table appreg.resolution_codes cascade;
truncate table appreg.standard_applicants cascade;
truncate table appreg.national_court_houses cascade;
truncate table appreg.data_audit cascade;
truncate table appreg.al_ale_sequence_mapping cascade;
truncate table appreg.appreg_user_mapping cascade;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    WHERE c.conrelid = 'appreg.app_list_entry_fee_id'::regclass
      AND c.conname  = 'ux_app_list_entry_fee_id_row'
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS ux_app_list_entry_fee_id_row_idx
      ON appreg.app_list_entry_fee_id
      (ale_ale_id, fee_fee_id, version, changed_by, changed_date, user_name);

    ALTER TABLE appreg.app_list_entry_fee_id
      ADD CONSTRAINT ux_app_list_entry_fee_id_row
      UNIQUE USING INDEX ux_app_list_entry_fee_id_row_idx;
  END IF;
END $$;

WITH cleaned AS (
SELECT
LEGACY_CHANGED_BY,
REPLACE(REPLACE(REPLACE(REPLACE(MODERN_CHANGED_BY,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS MODERN_CHANGED_BY
FROM appreg.appreg_user_mapping_temp
),
backslashes_fixed AS (
SELECT
LEGACY_CHANGED_BY,
REPLACE(MODERN_CHANGED_BY,'\\','\') AS MODERN_CHANGED_BY
FROM cleaned
)
INSERT INTO appreg.appreg_user_mapping AS t (
LEGACY_CHANGED_BY,
MODERN_CHANGED_BY
)
SELECT
LEGACY_CHANGED_BY,
left(MODERN_CHANGED_BY, 73)
FROM backslashes_fixed
ON CONFLICT (LEGACY_CHANGED_BY) DO UPDATE SET
MODERN_CHANGED_BY = EXCLUDED.MODERN_CHANGED_BY
;





WITH cleaned AS (
SELECT
AC_ID,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_CODE,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_CODE_TITLE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_CODE_TITLE,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_CODE_WORDING,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_CODE_WORDING,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_LEGISLATION,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_LEGISLATION,
REPLACE(REPLACE(REPLACE(REPLACE(FEE_DUE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FEE_DUE,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_CODE_RESPONDENT,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_CODE_RESPONDENT,
REPLACE(REPLACE(REPLACE(REPLACE(AC_DESTINATION_EMAIL_ADDRESS_1,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS AC_DESTINATION_EMAIL_ADDRESS_1,
REPLACE(REPLACE(REPLACE(REPLACE(AC_DESTINATION_EMAIL_ADDRESS_2,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS AC_DESTINATION_EMAIL_ADDRESS_2,
APPLICATION_CODE_START_DATE,
APPLICATION_CODE_END_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(BULK_RESPONDENT_ALLOWED,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS BULK_RESPONDENT_ALLOWED,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME,
REPLACE(REPLACE(REPLACE(REPLACE(AC_FEE_REFERENCE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS AC_FEE_REFERENCE
FROM appreg.application_codes_temp
),
backslashes_fixed AS (
SELECT
AC_ID,
REPLACE(APPLICATION_CODE,'\\','\') AS APPLICATION_CODE,
REPLACE(APPLICATION_CODE_TITLE,'\\','\') AS APPLICATION_CODE_TITLE,
REPLACE(APPLICATION_CODE_WORDING,'\\','\') AS APPLICATION_CODE_WORDING,
REPLACE(APPLICATION_LEGISLATION,'\\','\') AS APPLICATION_LEGISLATION,
REPLACE(FEE_DUE,'\\','\') AS FEE_DUE,
REPLACE(APPLICATION_CODE_RESPONDENT,'\\','\') AS APPLICATION_CODE_RESPONDENT,
REPLACE(AC_DESTINATION_EMAIL_ADDRESS_1,'\\','\') AS AC_DESTINATION_EMAIL_ADDRESS_1,
REPLACE(AC_DESTINATION_EMAIL_ADDRESS_2,'\\','\') AS AC_DESTINATION_EMAIL_ADDRESS_2,
APPLICATION_CODE_START_DATE,
APPLICATION_CODE_END_DATE,
REPLACE(BULK_RESPONDENT_ALLOWED,'\\','\') AS BULK_RESPONDENT_ALLOWED,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME,
REPLACE(AC_FEE_REFERENCE,'\\','\') AS AC_FEE_REFERENCE
FROM cleaned
)
INSERT INTO appreg.application_codes AS t (
AC_ID,
APPLICATION_CODE,
APPLICATION_CODE_TITLE,
APPLICATION_CODE_WORDING,
APPLICATION_LEGISLATION,
FEE_DUE,
APPLICATION_CODE_RESPONDENT,
AC_DESTINATION_EMAIL_ADDRESS_1,
AC_DESTINATION_EMAIL_ADDRESS_2,
APPLICATION_CODE_START_DATE,
APPLICATION_CODE_END_DATE,
BULK_RESPONDENT_ALLOWED,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME,
AC_FEE_REFERENCE
)
SELECT
AC_ID,
left(APPLICATION_CODE, 10),
left(APPLICATION_CODE_TITLE, 500),
APPLICATION_CODE_WORDING,
NULLIF(APPLICATION_LEGISLATION,''),
left(FEE_DUE,1),
left(APPLICATION_CODE_RESPONDENT,1),
NULLIF(left(AC_DESTINATION_EMAIL_ADDRESS_1, 253),''),
NULLIF(left(AC_DESTINATION_EMAIL_ADDRESS_2, 253),''),
(APPLICATION_CODE_START_DATE)::timestamp,
NULLIF(APPLICATION_CODE_END_DATE,'')::timestamp,
left(BULK_RESPONDENT_ALLOWED,1),
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),''),
NULLIF(left(AC_FEE_REFERENCE, 12),'')
FROM backslashes_fixed
ON CONFLICT (AC_ID) DO UPDATE SET
APPLICATION_CODE = EXCLUDED.APPLICATION_CODE,APPLICATION_CODE_TITLE = EXCLUDED.APPLICATION_CODE_TITLE,APPLICATION_CODE_WORDING = EXCLUDED.APPLICATION_CODE_WORDING,APPLICATION_LEGISLATION = EXCLUDED.APPLICATION_LEGISLATION,FEE_DUE = EXCLUDED.FEE_DUE,APPLICATION_CODE_RESPONDENT = EXCLUDED.APPLICATION_CODE_RESPONDENT,AC_DESTINATION_EMAIL_ADDRESS_1 = EXCLUDED.AC_DESTINATION_EMAIL_ADDRESS_1,AC_DESTINATION_EMAIL_ADDRESS_2 = EXCLUDED.AC_DESTINATION_EMAIL_ADDRESS_2,APPLICATION_CODE_START_DATE = EXCLUDED.APPLICATION_CODE_START_DATE,APPLICATION_CODE_END_DATE = EXCLUDED.APPLICATION_CODE_END_DATE,BULK_RESPONDENT_ALLOWED = EXCLUDED.BULK_RESPONDENT_ALLOWED,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME,AC_FEE_REFERENCE = EXCLUDED.AC_FEE_REFERENCE
;





WITH cleaned AS (
SELECT
CJA_ID,
REPLACE(REPLACE(REPLACE(REPLACE(CJA_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS CJA_CODE,
REPLACE(REPLACE(REPLACE(REPLACE(CJA_DESCRIPTION,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS CJA_DESCRIPTION
FROM appreg.criminal_justice_area_temp
),
backslashes_fixed AS (
SELECT
CJA_ID,
REPLACE(CJA_CODE,'\\','\') AS CJA_CODE,
REPLACE(CJA_DESCRIPTION,'\\','\') AS CJA_DESCRIPTION
FROM cleaned
)
INSERT INTO appreg.criminal_justice_area AS t (
CJA_ID,
CJA_CODE,
CJA_DESCRIPTION
)
SELECT
CJA_ID,
left(CJA_CODE, 2),
left(CJA_DESCRIPTION, 35)
FROM backslashes_fixed
ON CONFLICT (CJA_ID) DO UPDATE SET
CJA_CODE = EXCLUDED.CJA_CODE,CJA_DESCRIPTION = EXCLUDED.CJA_DESCRIPTION
;





WITH cleaned AS (
SELECT
AL_ID,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_LIST_STATUS,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_LIST_STATUS,
APPLICATION_LIST_DATE,
APPLICATION_LIST_TIME,
REPLACE(REPLACE(REPLACE(REPLACE(COURTHOUSE_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS COURTHOUSE_CODE,
REPLACE(REPLACE(REPLACE(REPLACE(OTHER_COURTHOUSE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS OTHER_COURTHOUSE,
REPLACE(REPLACE(REPLACE(REPLACE(LIST_DESCRIPTION,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS LIST_DESCRIPTION,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME,
REPLACE(REPLACE(REPLACE(REPLACE(COURTHOUSE_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS COURTHOUSE_NAME,
DURATION_HOUR,
DURATION_MINUTE,
CJA_CJA_ID
FROM appreg.application_lists_temp
),
backslashes_fixed AS (
SELECT
AL_ID,
REPLACE(APPLICATION_LIST_STATUS,'\\','\') AS APPLICATION_LIST_STATUS,
APPLICATION_LIST_DATE,
APPLICATION_LIST_TIME,
REPLACE(COURTHOUSE_CODE,'\\','\') AS COURTHOUSE_CODE,
REPLACE(OTHER_COURTHOUSE,'\\','\') AS OTHER_COURTHOUSE,
REPLACE(LIST_DESCRIPTION,'\\','\') AS LIST_DESCRIPTION,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME,
REPLACE(COURTHOUSE_NAME,'\\','\') AS COURTHOUSE_NAME,
DURATION_HOUR,
DURATION_MINUTE,
CJA_CJA_ID
FROM cleaned
)
INSERT INTO appreg.application_lists AS t (
AL_ID,
APPLICATION_LIST_STATUS,
APPLICATION_LIST_DATE,
APPLICATION_LIST_TIME,
COURTHOUSE_CODE,
OTHER_COURTHOUSE,
LIST_DESCRIPTION,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME,
COURTHOUSE_NAME,
DURATION_HOUR,
DURATION_MINUTE,
CJA_CJA_ID
)
SELECT
AL_ID,
NULLIF(left(APPLICATION_LIST_STATUS, 7),''),
(APPLICATION_LIST_DATE)::timestamp,
(APPLICATION_LIST_TIME)::timestamp,
NULLIF(left(COURTHOUSE_CODE, 10),''),
NULLIF(left(OTHER_COURTHOUSE, 200),''),
left(LIST_DESCRIPTION, 200),
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),''),
NULLIF(left(COURTHOUSE_NAME, 200),''),
DURATION_HOUR,
DURATION_MINUTE,
CJA_CJA_ID
FROM backslashes_fixed
ON CONFLICT (AL_ID) DO UPDATE SET
APPLICATION_LIST_STATUS = EXCLUDED.APPLICATION_LIST_STATUS,APPLICATION_LIST_DATE = EXCLUDED.APPLICATION_LIST_DATE,APPLICATION_LIST_TIME = EXCLUDED.APPLICATION_LIST_TIME,COURTHOUSE_CODE = EXCLUDED.COURTHOUSE_CODE,OTHER_COURTHOUSE = EXCLUDED.OTHER_COURTHOUSE,LIST_DESCRIPTION = EXCLUDED.LIST_DESCRIPTION,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME,COURTHOUSE_NAME = EXCLUDED.COURTHOUSE_NAME,DURATION_HOUR = EXCLUDED.DURATION_HOUR,DURATION_MINUTE = EXCLUDED.DURATION_MINUTE,CJA_CJA_ID = EXCLUDED.CJA_CJA_ID
;





WITH cleaned AS (
SELECT
SA_ID,
REPLACE(REPLACE(REPLACE(REPLACE(STANDARD_APPLICANT_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS STANDARD_APPLICANT_CODE,
STANDARD_APPLICANT_START_DATE,
STANDARD_APPLICANT_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME,
REPLACE(REPLACE(REPLACE(REPLACE(NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS NAME,
REPLACE(REPLACE(REPLACE(REPLACE(TITLE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TITLE,
REPLACE(REPLACE(REPLACE(REPLACE(FORENAME_1,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FORENAME_1,
REPLACE(REPLACE(REPLACE(REPLACE(FORENAME_2,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FORENAME_2,
REPLACE(REPLACE(REPLACE(REPLACE(FORENAME_3,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FORENAME_3,
REPLACE(REPLACE(REPLACE(REPLACE(SURNAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS SURNAME,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L1,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L1,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L2,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L2,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L3,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L3,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L4,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L4,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L5,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L5,
REPLACE(REPLACE(REPLACE(REPLACE(POSTCODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS POSTCODE,
REPLACE(REPLACE(REPLACE(REPLACE(EMAIL_ADDRESS,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS EMAIL_ADDRESS,
REPLACE(REPLACE(REPLACE(REPLACE(TELEPHONE_NUMBER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TELEPHONE_NUMBER,
REPLACE(REPLACE(REPLACE(REPLACE(MOBILE_NUMBER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS MOBILE_NUMBER
FROM appreg.standard_applicants_temp
),
backslashes_fixed AS (
SELECT
SA_ID,
REPLACE(STANDARD_APPLICANT_CODE,'\\','\') AS STANDARD_APPLICANT_CODE,
STANDARD_APPLICANT_START_DATE,
STANDARD_APPLICANT_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME,
REPLACE(NAME,'\\','\') AS NAME,
REPLACE(TITLE,'\\','\') AS TITLE,
REPLACE(FORENAME_1,'\\','\') AS FORENAME_1,
REPLACE(FORENAME_2,'\\','\') AS FORENAME_2,
REPLACE(FORENAME_3,'\\','\') AS FORENAME_3,
REPLACE(SURNAME,'\\','\') AS SURNAME,
REPLACE(ADDRESS_L1,'\\','\') AS ADDRESS_L1,
REPLACE(ADDRESS_L2,'\\','\') AS ADDRESS_L2,
REPLACE(ADDRESS_L3,'\\','\') AS ADDRESS_L3,
REPLACE(ADDRESS_L4,'\\','\') AS ADDRESS_L4,
REPLACE(ADDRESS_L5,'\\','\') AS ADDRESS_L5,
REPLACE(POSTCODE,'\\','\') AS POSTCODE,
REPLACE(EMAIL_ADDRESS,'\\','\') AS EMAIL_ADDRESS,
REPLACE(TELEPHONE_NUMBER,'\\','\') AS TELEPHONE_NUMBER,
REPLACE(MOBILE_NUMBER,'\\','\') AS MOBILE_NUMBER
FROM cleaned
)
INSERT INTO appreg.standard_applicants AS t (
SA_ID,
STANDARD_APPLICANT_CODE,
STANDARD_APPLICANT_START_DATE,
STANDARD_APPLICANT_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME,
NAME,
TITLE,
FORENAME_1,
FORENAME_2,
FORENAME_3,
SURNAME,
ADDRESS_L1,
ADDRESS_L2,
ADDRESS_L3,
ADDRESS_L4,
ADDRESS_L5,
POSTCODE,
EMAIL_ADDRESS,
TELEPHONE_NUMBER,
MOBILE_NUMBER
)
SELECT
SA_ID,
left(STANDARD_APPLICANT_CODE, 10),
(STANDARD_APPLICANT_START_DATE)::timestamp,
NULLIF(STANDARD_APPLICANT_END_DATE,'')::timestamp,
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),''),
NULLIF(left(NAME, 100),''),
NULLIF(left(TITLE, 100),''),
NULLIF(left(FORENAME_1, 100),''),
NULLIF(left(FORENAME_2, 100),''),
NULLIF(left(FORENAME_3, 100),''),
NULLIF(left(SURNAME, 100),''),
left(ADDRESS_L1, 35),
NULLIF(left(ADDRESS_L2, 35),''),
NULLIF(left(ADDRESS_L3, 35),''),
NULLIF(left(ADDRESS_L4, 35),''),
NULLIF(left(ADDRESS_L5, 35),''),
NULLIF(left(POSTCODE, 8),''),
NULLIF(left(EMAIL_ADDRESS, 253),''),
NULLIF(left(TELEPHONE_NUMBER, 20),''),
NULLIF(left(MOBILE_NUMBER, 20),'')
FROM backslashes_fixed
ON CONFLICT (SA_ID) DO UPDATE SET
STANDARD_APPLICANT_CODE = EXCLUDED.STANDARD_APPLICANT_CODE,STANDARD_APPLICANT_START_DATE = EXCLUDED.STANDARD_APPLICANT_START_DATE,STANDARD_APPLICANT_END_DATE = EXCLUDED.STANDARD_APPLICANT_END_DATE,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME,NAME = EXCLUDED.NAME,TITLE = EXCLUDED.TITLE,FORENAME_1 = EXCLUDED.FORENAME_1,FORENAME_2 = EXCLUDED.FORENAME_2,FORENAME_3 = EXCLUDED.FORENAME_3,SURNAME = EXCLUDED.SURNAME,ADDRESS_L1 = EXCLUDED.ADDRESS_L1,ADDRESS_L2 = EXCLUDED.ADDRESS_L2,ADDRESS_L3 = EXCLUDED.ADDRESS_L3,ADDRESS_L4 = EXCLUDED.ADDRESS_L4,ADDRESS_L5 = EXCLUDED.ADDRESS_L5,POSTCODE = EXCLUDED.POSTCODE,EMAIL_ADDRESS = EXCLUDED.EMAIL_ADDRESS,TELEPHONE_NUMBER = EXCLUDED.TELEPHONE_NUMBER,MOBILE_NUMBER = EXCLUDED.MOBILE_NUMBER
;





WITH cleaned AS (
SELECT
NA_ID,
REPLACE(REPLACE(REPLACE(REPLACE(CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS CODE,
REPLACE(REPLACE(REPLACE(REPLACE(NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS NAME,
REPLACE(REPLACE(REPLACE(REPLACE(TITLE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TITLE,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L1,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L1,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L2,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L2,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L3,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L3,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L4,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L4,
REPLACE(REPLACE(REPLACE(REPLACE(ADDRESS_L5,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ADDRESS_L5,
REPLACE(REPLACE(REPLACE(REPLACE(POSTCODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS POSTCODE,
REPLACE(REPLACE(REPLACE(REPLACE(EMAIL_ADDRESS,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS EMAIL_ADDRESS,
REPLACE(REPLACE(REPLACE(REPLACE(TELEPHONE_NUMBER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TELEPHONE_NUMBER,
REPLACE(REPLACE(REPLACE(REPLACE(MOBILE_NUMBER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS MOBILE_NUMBER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME,
DATE_OF_BIRTH,
REPLACE(REPLACE(REPLACE(REPLACE(DMS_ID,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS DMS_ID
,REPLACE(REPLACE(REPLACE(REPLACE(FIRST_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FIRST_NAME,REPLACE(REPLACE(REPLACE(REPLACE(MIDDLE_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS MIDDLE_NAME,REPLACE(REPLACE(REPLACE(REPLACE(LAST_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS LAST_NAME
FROM appreg.name_address_temp
),
backslashes_fixed AS (
SELECT
NA_ID,
REPLACE(CODE,'\\','\') AS CODE,
REPLACE(NAME,'\\','\') AS NAME,
REPLACE(TITLE,'\\','\') AS TITLE,
REPLACE(ADDRESS_L1,'\\','\') AS ADDRESS_L1,
REPLACE(ADDRESS_L2,'\\','\') AS ADDRESS_L2,
REPLACE(ADDRESS_L3,'\\','\') AS ADDRESS_L3,
REPLACE(ADDRESS_L4,'\\','\') AS ADDRESS_L4,
REPLACE(ADDRESS_L5,'\\','\') AS ADDRESS_L5,
REPLACE(POSTCODE,'\\','\') AS POSTCODE,
REPLACE(EMAIL_ADDRESS,'\\','\') AS EMAIL_ADDRESS,
REPLACE(TELEPHONE_NUMBER,'\\','\') AS TELEPHONE_NUMBER,
REPLACE(MOBILE_NUMBER,'\\','\') AS MOBILE_NUMBER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME,
DATE_OF_BIRTH,
REPLACE(DMS_ID,'\\','\') AS DMS_ID
,REPLACE(FIRST_NAME,'\','\') AS FIRST_NAME,REPLACE(MIDDLE_NAME,'\','\') AS MIDDLE_NAME,REPLACE(LAST_NAME,'\','\') AS LAST_NAME
FROM cleaned
)
INSERT INTO appreg.name_address AS t (
NA_ID,
CODE,
NAME,
TITLE,
ADDRESS_L1,
ADDRESS_L2,
ADDRESS_L3,
ADDRESS_L4,
ADDRESS_L5,
POSTCODE,
EMAIL_ADDRESS,
TELEPHONE_NUMBER,
MOBILE_NUMBER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME,
DATE_OF_BIRTH,
DMS_ID
, FIRST_NAME, MIDDLE_NAME, LAST_NAME
)
SELECT
NA_ID,
NULLIF(left(CODE, 10),''),
NULLIF(left(NAME, 100),''),
NULLIF(left(TITLE, 100),''),
left(ADDRESS_L1, 35),
NULLIF(left(ADDRESS_L2, 35),''),
NULLIF(left(ADDRESS_L3, 35),''),
NULLIF(left(ADDRESS_L4, 35),''),
NULLIF(left(ADDRESS_L5, 35),''),
NULLIF(left(POSTCODE, 8),''),
NULLIF(left(EMAIL_ADDRESS, 253),''),
NULLIF(left(TELEPHONE_NUMBER, 20),''),
NULLIF(left(MOBILE_NUMBER, 20),''),
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),''),
NULLIF(DATE_OF_BIRTH,'')::timestamp,
NULLIF(left(DMS_ID, 20),'')
,NULLIF(left(FIRST_NAME, 100),''),NULLIF(left(MIDDLE_NAME, 100),''),NULLIF(left(LAST_NAME, 100),'')
FROM backslashes_fixed
ON CONFLICT (NA_ID) DO UPDATE SET
CODE = EXCLUDED.CODE,NAME = EXCLUDED.NAME,TITLE = EXCLUDED.TITLE,ADDRESS_L1 = EXCLUDED.ADDRESS_L1,ADDRESS_L2 = EXCLUDED.ADDRESS_L2,ADDRESS_L3 = EXCLUDED.ADDRESS_L3,ADDRESS_L4 = EXCLUDED.ADDRESS_L4,ADDRESS_L5 = EXCLUDED.ADDRESS_L5,POSTCODE = EXCLUDED.POSTCODE,EMAIL_ADDRESS = EXCLUDED.EMAIL_ADDRESS,TELEPHONE_NUMBER = EXCLUDED.TELEPHONE_NUMBER,MOBILE_NUMBER = EXCLUDED.MOBILE_NUMBER,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME,DATE_OF_BIRTH = EXCLUDED.DATE_OF_BIRTH,DMS_ID = EXCLUDED.DMS_ID
, FIRST_NAME = EXCLUDED.FIRST_NAME, MIDDLE_NAME = EXCLUDED.MIDDLE_NAME, LAST_NAME = EXCLUDED.LAST_NAME
;





WITH cleaned AS (
SELECT
ALE_ID,
AL_AL_ID,
SA_SA_ID,
AC_AC_ID,
A_NA_ID,
R_NA_ID,
NUMBER_OF_BULK_RESPONDENTS,
REPLACE(REPLACE(REPLACE(REPLACE(APPLICATION_LIST_ENTRY_WORDING,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS APPLICATION_LIST_ENTRY_WORDING,
REPLACE(REPLACE(REPLACE(REPLACE(CASE_REFERENCE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS CASE_REFERENCE,
REPLACE(REPLACE(REPLACE(REPLACE(ACCOUNT_NUMBER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ACCOUNT_NUMBER,
REPLACE(REPLACE(REPLACE(REPLACE(ENTRY_RESCHEDULED,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ENTRY_RESCHEDULED,
REPLACE(REPLACE(REPLACE(REPLACE(NOTES,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS NOTES,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(BULK_UPLOAD,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS BULK_UPLOAD,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME,
SEQUENCE_NUMBER,
REPLACE(REPLACE(REPLACE(REPLACE(TCEP_STATUS,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TCEP_STATUS,
REPLACE(REPLACE(REPLACE(REPLACE(MESSAGE_UUID,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS MESSAGE_UUID,
REPLACE(REPLACE(REPLACE(REPLACE(RETRY_COUNT,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RETRY_COUNT,
LODGEMENT_DATE
FROM appreg.application_list_entries_temp
),
backslashes_fixed AS (
SELECT
ALE_ID,
AL_AL_ID,
SA_SA_ID,
AC_AC_ID,
A_NA_ID,
R_NA_ID,
NUMBER_OF_BULK_RESPONDENTS,
REPLACE(APPLICATION_LIST_ENTRY_WORDING,'\\','\') AS APPLICATION_LIST_ENTRY_WORDING,
REPLACE(CASE_REFERENCE,'\\','\') AS CASE_REFERENCE,
REPLACE(ACCOUNT_NUMBER,'\\','\') AS ACCOUNT_NUMBER,
REPLACE(ENTRY_RESCHEDULED,'\\','\') AS ENTRY_RESCHEDULED,
REPLACE(NOTES,'\\','\') AS NOTES,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(BULK_UPLOAD,'\\','\') AS BULK_UPLOAD,
REPLACE(USER_NAME,'\\','\') AS USER_NAME,
SEQUENCE_NUMBER,
REPLACE(TCEP_STATUS,'\\','\') AS TCEP_STATUS,
REPLACE(MESSAGE_UUID,'\\','\') AS MESSAGE_UUID,
REPLACE(RETRY_COUNT,'\\','\') AS RETRY_COUNT,
LODGEMENT_DATE
FROM cleaned
)
INSERT INTO appreg.application_list_entries AS t (
ALE_ID,
AL_AL_ID,
SA_SA_ID,
AC_AC_ID,
A_NA_ID,
R_NA_ID,
NUMBER_OF_BULK_RESPONDENTS,
APPLICATION_LIST_ENTRY_WORDING,
CASE_REFERENCE,
ACCOUNT_NUMBER,
ENTRY_RESCHEDULED,
NOTES,
VERSION,
CHANGED_BY,
CHANGED_DATE,
BULK_UPLOAD,
USER_NAME,
SEQUENCE_NUMBER,
TCEP_STATUS,
MESSAGE_UUID,
RETRY_COUNT,
LODGEMENT_DATE
)
SELECT
ALE_ID,
AL_AL_ID,
SA_SA_ID,
AC_AC_ID,
A_NA_ID,
R_NA_ID,
NUMBER_OF_BULK_RESPONDENTS,
APPLICATION_LIST_ENTRY_WORDING,
NULLIF(left(CASE_REFERENCE, 15),''),
NULLIF(left(ACCOUNT_NUMBER, 20),''),
left(ENTRY_RESCHEDULED,1),
NULLIF(left(NOTES, 4000),''),
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(BULK_UPLOAD, 1),''),
NULLIF(left(USER_NAME, 250),''),
SEQUENCE_NUMBER,
NULLIF(left(TCEP_STATUS, 2),''),
NULLIF(left(MESSAGE_UUID, 36),''),
NULLIF(left(RETRY_COUNT, 36),''),
(LODGEMENT_DATE)::timestamp
FROM backslashes_fixed
ON CONFLICT (ALE_ID) DO UPDATE SET
AL_AL_ID = EXCLUDED.AL_AL_ID,SA_SA_ID = EXCLUDED.SA_SA_ID,AC_AC_ID = EXCLUDED.AC_AC_ID,A_NA_ID = EXCLUDED.A_NA_ID,R_NA_ID = EXCLUDED.R_NA_ID,NUMBER_OF_BULK_RESPONDENTS = EXCLUDED.NUMBER_OF_BULK_RESPONDENTS,APPLICATION_LIST_ENTRY_WORDING = EXCLUDED.APPLICATION_LIST_ENTRY_WORDING,CASE_REFERENCE = EXCLUDED.CASE_REFERENCE,ACCOUNT_NUMBER = EXCLUDED.ACCOUNT_NUMBER,ENTRY_RESCHEDULED = EXCLUDED.ENTRY_RESCHEDULED,NOTES = EXCLUDED.NOTES,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,BULK_UPLOAD = EXCLUDED.BULK_UPLOAD,USER_NAME = EXCLUDED.USER_NAME,SEQUENCE_NUMBER = EXCLUDED.SEQUENCE_NUMBER,TCEP_STATUS = EXCLUDED.TCEP_STATUS,MESSAGE_UUID = EXCLUDED.MESSAGE_UUID,RETRY_COUNT = EXCLUDED.RETRY_COUNT,LODGEMENT_DATE = EXCLUDED.LODGEMENT_DATE
;





WITH unescaped AS (
SELECT
AR_ID,
AL_AL_ID,
piece_no,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TEXT,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n'), '\\', '\') AS piece,
CHANGED_BY,
(CHANGED_DATE)::timestamptz AS CHANGED_DATE,
NULLIF(USER_NAME,'')::varchar(250) AS USER_NAME
FROM appreg.application_register_temp
),
reconstructed AS (
SELECT
AR_ID,
MIN(AL_AL_ID) AS AL_AL_ID,
string_agg(piece, '' ORDER BY piece_no) AS text_full,
MIN(CHANGED_BY) AS CHANGED_BY,
MIN(CHANGED_DATE) AS CHANGED_DATE,
MIN(USER_NAME) AS USER_NAME
FROM unescaped
GROUP BY AR_ID
)
INSERT INTO appreg.application_register AS t (
AR_ID,
AL_AL_ID,
TEXT,
CHANGED_BY,
CHANGED_DATE,
USER_NAME
)
SELECT
r.AR_ID,
r.AL_AL_ID,
NULLIF(r.TEXT_full,'') AS TEXT,
r.CHANGED_BY,
r.CHANGED_DATE,
r.USER_NAME
FROM reconstructed r
ON CONFLICT (AR_ID) DO UPDATE SET
AL_AL_ID = EXCLUDED.AL_AL_ID,TEXT = EXCLUDED.TEXT,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME
;



WITH cleaned AS (
SELECT
FEE_ID,
REPLACE(REPLACE(REPLACE(REPLACE(FEE_REFERENCE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FEE_REFERENCE,
REPLACE(REPLACE(REPLACE(REPLACE(FEE_DESCRIPTION,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FEE_DESCRIPTION,
FEE_VALUE,
FEE_START_DATE,
FEE_END_DATE,
FEE_VERSION,
FEE_CHANGED_BY,
FEE_CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(FEE_USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FEE_USER_NAME
FROM appreg.fee_temp
),
backslashes_fixed AS (
SELECT
FEE_ID,
REPLACE(FEE_REFERENCE,'\\','\') AS FEE_REFERENCE,
REPLACE(FEE_DESCRIPTION,'\\','\') AS FEE_DESCRIPTION,
FEE_VALUE,
FEE_START_DATE,
FEE_END_DATE,
FEE_VERSION,
FEE_CHANGED_BY,
FEE_CHANGED_DATE,
REPLACE(FEE_USER_NAME,'\\','\') AS FEE_USER_NAME
FROM cleaned
)
INSERT INTO appreg.fee AS t (
FEE_ID,
FEE_REFERENCE,
FEE_DESCRIPTION,
FEE_VALUE,
FEE_START_DATE,
FEE_END_DATE,
FEE_VERSION,
FEE_CHANGED_BY,
FEE_CHANGED_DATE,
FEE_USER_NAME
)
SELECT
FEE_ID,
left(FEE_REFERENCE, 12),
left(FEE_DESCRIPTION, 250),
FEE_VALUE,
(FEE_START_DATE)::timestamp,
NULLIF(FEE_END_DATE,'')::timestamp,
FEE_VERSION,
FEE_CHANGED_BY,
(FEE_CHANGED_DATE)::timestamp,
left(FEE_USER_NAME, 250)
FROM backslashes_fixed
ON CONFLICT (FEE_ID) DO UPDATE SET
FEE_REFERENCE = EXCLUDED.FEE_REFERENCE,FEE_DESCRIPTION = EXCLUDED.FEE_DESCRIPTION,FEE_VALUE = EXCLUDED.FEE_VALUE,FEE_START_DATE = EXCLUDED.FEE_START_DATE,FEE_END_DATE = EXCLUDED.FEE_END_DATE,FEE_VERSION = EXCLUDED.FEE_VERSION,FEE_CHANGED_BY = EXCLUDED.FEE_CHANGED_BY,FEE_CHANGED_DATE = EXCLUDED.FEE_CHANGED_DATE,FEE_USER_NAME = EXCLUDED.FEE_USER_NAME
;



UPDATE appreg.fee SET is_offsite=true WHERE fee_reference='CO1.1';

WITH cleaned AS (
SELECT
ALE_ALE_ID,
FEE_FEE_ID,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME
FROM appreg.app_list_entry_fee_id_temp
),
backslashes_fixed AS (
SELECT
ALE_ALE_ID,
FEE_FEE_ID,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME
FROM cleaned
)
INSERT INTO appreg.app_list_entry_fee_id AS t (
ALE_ALE_ID,
FEE_FEE_ID,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME
)
SELECT
ALE_ALE_ID,
FEE_FEE_ID,
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
left(USER_NAME, 250)
FROM backslashes_fixed
ON CONFLICT ON CONSTRAINT ux_app_list_entry_fee_id_row DO UPDATE SET
ALE_ALE_ID = EXCLUDED.ALE_ALE_ID,FEE_FEE_ID = EXCLUDED.FEE_FEE_ID,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME
;

alter table appreg.app_list_entry_fee_id drop constraint ux_app_list_entry_fee_id_row;



WITH cleaned AS (
SELECT
ALEFS_ID,
ALEFS_ALE_ID,
REPLACE(REPLACE(REPLACE(REPLACE(ALEFS_PAYMENT_REFERENCE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ALEFS_PAYMENT_REFERENCE,
REPLACE(REPLACE(REPLACE(REPLACE(ALEFS_FEE_STATUS,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ALEFS_FEE_STATUS,
ALEFS_FEE_STATUS_DATE,
ALEFS_VERSION,
ALEFS_CHANGED_BY,
ALEFS_CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(ALEFS_USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS ALEFS_USER_NAME,
ALEFS_STATUS_CREATION_DATE
FROM appreg.app_list_entry_fee_status_temp
),
backslashes_fixed AS (
SELECT
ALEFS_ID,
ALEFS_ALE_ID,
REPLACE(ALEFS_PAYMENT_REFERENCE,'\\','\') AS ALEFS_PAYMENT_REFERENCE,
REPLACE(ALEFS_FEE_STATUS,'\\','\') AS ALEFS_FEE_STATUS,
ALEFS_FEE_STATUS_DATE,
ALEFS_VERSION,
ALEFS_CHANGED_BY,
ALEFS_CHANGED_DATE,
REPLACE(ALEFS_USER_NAME,'\\','\') AS ALEFS_USER_NAME,
ALEFS_STATUS_CREATION_DATE
FROM cleaned
)
INSERT INTO appreg.app_list_entry_fee_status AS t (
ALEFS_ID,
ALEFS_ALE_ID,
ALEFS_PAYMENT_REFERENCE,
ALEFS_FEE_STATUS,
ALEFS_FEE_STATUS_DATE,
ALEFS_VERSION,
ALEFS_CHANGED_BY,
ALEFS_CHANGED_DATE,
ALEFS_USER_NAME,
ALEFS_STATUS_CREATION_DATE
)
SELECT
ALEFS_ID,
ALEFS_ALE_ID,
NULLIF(left(ALEFS_PAYMENT_REFERENCE, 15),''),
left(ALEFS_FEE_STATUS, 1),
(ALEFS_FEE_STATUS_DATE)::timestamp,
ALEFS_VERSION,
ALEFS_CHANGED_BY,
(ALEFS_CHANGED_DATE)::timestamp,
left(ALEFS_USER_NAME, 250),
NULLIF(ALEFS_STATUS_CREATION_DATE,'')::timestamp
FROM backslashes_fixed
ON CONFLICT (ALEFS_ID) DO UPDATE SET
ALEFS_ALE_ID = EXCLUDED.ALEFS_ALE_ID,ALEFS_PAYMENT_REFERENCE = EXCLUDED.ALEFS_PAYMENT_REFERENCE,ALEFS_FEE_STATUS = EXCLUDED.ALEFS_FEE_STATUS,ALEFS_FEE_STATUS_DATE = EXCLUDED.ALEFS_FEE_STATUS_DATE,ALEFS_VERSION = EXCLUDED.ALEFS_VERSION,ALEFS_CHANGED_BY = EXCLUDED.ALEFS_CHANGED_BY,ALEFS_CHANGED_DATE = EXCLUDED.ALEFS_CHANGED_DATE,ALEFS_USER_NAME = EXCLUDED.ALEFS_USER_NAME,ALEFS_STATUS_CREATION_DATE = EXCLUDED.ALEFS_STATUS_CREATION_DATE
;





WITH cleaned AS (
SELECT
ALEO_ID,
ALE_ALE_ID,
REPLACE(REPLACE(REPLACE(REPLACE(TITLE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS TITLE,
REPLACE(REPLACE(REPLACE(REPLACE(FORENAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS FORENAME,
REPLACE(REPLACE(REPLACE(REPLACE(SURNAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS SURNAME,
REPLACE(REPLACE(REPLACE(REPLACE(OFFICIAL_TYPE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS OFFICIAL_TYPE,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME
FROM appreg.app_list_entry_official_temp
),
backslashes_fixed AS (
SELECT
ALEO_ID,
ALE_ALE_ID,
REPLACE(TITLE,'\\','\') AS TITLE,
REPLACE(FORENAME,'\\','\') AS FORENAME,
REPLACE(SURNAME,'\\','\') AS SURNAME,
REPLACE(OFFICIAL_TYPE,'\\','\') AS OFFICIAL_TYPE,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME
FROM cleaned
)
INSERT INTO appreg.app_list_entry_official AS t (
ALEO_ID,
ALE_ALE_ID,
TITLE,
FORENAME,
SURNAME,
OFFICIAL_TYPE,
CHANGED_BY,
CHANGED_DATE,
USER_NAME
)
SELECT
ALEO_ID,
ALE_ALE_ID,
NULLIF(left(TITLE, 100),''),
NULLIF(left(FORENAME, 100),''),
NULLIF(left(SURNAME, 100),''),
left(OFFICIAL_TYPE, 1),
CHANGED_BY,
(CHANGED_DATE)::timestamp,
left(USER_NAME, 250)
FROM backslashes_fixed
ON CONFLICT (ALEO_ID) DO UPDATE SET
ALE_ALE_ID = EXCLUDED.ALE_ALE_ID,TITLE = EXCLUDED.TITLE,FORENAME = EXCLUDED.FORENAME,SURNAME = EXCLUDED.SURNAME,OFFICIAL_TYPE = EXCLUDED.OFFICIAL_TYPE,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME
;





WITH cleaned AS (
SELECT
RC_ID,
REPLACE(REPLACE(REPLACE(REPLACE(RESOLUTION_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RESOLUTION_CODE,
REPLACE(REPLACE(REPLACE(REPLACE(RESOLUTION_CODE_TITLE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RESOLUTION_CODE_TITLE,
REPLACE(REPLACE(REPLACE(REPLACE(RESOLUTION_CODE_WORDING,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RESOLUTION_CODE_WORDING,
REPLACE(REPLACE(REPLACE(REPLACE(RESOLUTION_LEGISLATION,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RESOLUTION_LEGISLATION,
REPLACE(REPLACE(REPLACE(REPLACE(RC_DESTINATION_EMAIL_ADDRESS_1,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RC_DESTINATION_EMAIL_ADDRESS_1,
REPLACE(REPLACE(REPLACE(REPLACE(RC_DESTINATION_EMAIL_ADDRESS_2,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS RC_DESTINATION_EMAIL_ADDRESS_2,
RESOLUTION_CODE_START_DATE,
RESOLUTION_CODE_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME
FROM appreg.resolution_codes_temp
),
backslashes_fixed AS (
SELECT
RC_ID,
REPLACE(RESOLUTION_CODE,'\\','\') AS RESOLUTION_CODE,
REPLACE(RESOLUTION_CODE_TITLE,'\\','\') AS RESOLUTION_CODE_TITLE,
REPLACE(RESOLUTION_CODE_WORDING,'\\','\') AS RESOLUTION_CODE_WORDING,
REPLACE(RESOLUTION_LEGISLATION,'\\','\') AS RESOLUTION_LEGISLATION,
REPLACE(RC_DESTINATION_EMAIL_ADDRESS_1,'\\','\') AS RC_DESTINATION_EMAIL_ADDRESS_1,
REPLACE(RC_DESTINATION_EMAIL_ADDRESS_2,'\\','\') AS RC_DESTINATION_EMAIL_ADDRESS_2,
RESOLUTION_CODE_START_DATE,
RESOLUTION_CODE_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME
FROM cleaned
)
INSERT INTO appreg.resolution_codes AS t (
RC_ID,
RESOLUTION_CODE,
RESOLUTION_CODE_TITLE,
RESOLUTION_CODE_WORDING,
RESOLUTION_LEGISLATION,
RC_DESTINATION_EMAIL_ADDRESS_1,
RC_DESTINATION_EMAIL_ADDRESS_2,
RESOLUTION_CODE_START_DATE,
RESOLUTION_CODE_END_DATE,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME
)
SELECT
RC_ID,
left(RESOLUTION_CODE, 10),
left(RESOLUTION_CODE_TITLE, 500),
RESOLUTION_CODE_WORDING,
NULLIF(RESOLUTION_LEGISLATION,''),
NULLIF(left(RC_DESTINATION_EMAIL_ADDRESS_1, 253),''),
NULLIF(left(RC_DESTINATION_EMAIL_ADDRESS_2, 253),''),
(RESOLUTION_CODE_START_DATE)::timestamp,
NULLIF(RESOLUTION_CODE_END_DATE,'')::timestamp,
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),'')
FROM backslashes_fixed
ON CONFLICT (RC_ID) DO UPDATE SET
RESOLUTION_CODE = EXCLUDED.RESOLUTION_CODE,RESOLUTION_CODE_TITLE = EXCLUDED.RESOLUTION_CODE_TITLE,RESOLUTION_CODE_WORDING = EXCLUDED.RESOLUTION_CODE_WORDING,RESOLUTION_LEGISLATION = EXCLUDED.RESOLUTION_LEGISLATION,RC_DESTINATION_EMAIL_ADDRESS_1 = EXCLUDED.RC_DESTINATION_EMAIL_ADDRESS_1,RC_DESTINATION_EMAIL_ADDRESS_2 = EXCLUDED.RC_DESTINATION_EMAIL_ADDRESS_2,RESOLUTION_CODE_START_DATE = EXCLUDED.RESOLUTION_CODE_START_DATE,RESOLUTION_CODE_END_DATE = EXCLUDED.RESOLUTION_CODE_END_DATE,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME
;





WITH cleaned AS (
SELECT
ALER_ID,
RC_RC_ID,
ALE_ALE_ID,
REPLACE(REPLACE(REPLACE(REPLACE(AL_ENTRY_RESOLUTION_WORDING,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS AL_ENTRY_RESOLUTION_WORDING,
REPLACE(REPLACE(REPLACE(REPLACE(AL_ENTRY_RESOLUTION_OFFICER,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS AL_ENTRY_RESOLUTION_OFFICER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(USER_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS USER_NAME
FROM appreg.app_list_entry_resolutions_temp
),
backslashes_fixed AS (
SELECT
ALER_ID,
RC_RC_ID,
ALE_ALE_ID,
REPLACE(AL_ENTRY_RESOLUTION_WORDING,'\\','\') AS AL_ENTRY_RESOLUTION_WORDING,
REPLACE(AL_ENTRY_RESOLUTION_OFFICER,'\\','\') AS AL_ENTRY_RESOLUTION_OFFICER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
REPLACE(USER_NAME,'\\','\') AS USER_NAME
FROM cleaned
)
INSERT INTO appreg.app_list_entry_resolutions AS t (
ALER_ID,
RC_RC_ID,
ALE_ALE_ID,
AL_ENTRY_RESOLUTION_WORDING,
AL_ENTRY_RESOLUTION_OFFICER,
VERSION,
CHANGED_BY,
CHANGED_DATE,
USER_NAME
)
SELECT
ALER_ID,
RC_RC_ID,
ALE_ALE_ID,
AL_ENTRY_RESOLUTION_WORDING,
left(AL_ENTRY_RESOLUTION_OFFICER, 1000),
VERSION,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
NULLIF(left(USER_NAME, 250),'')
FROM backslashes_fixed
ON CONFLICT (ALER_ID) DO UPDATE SET
RC_RC_ID = EXCLUDED.RC_RC_ID,ALE_ALE_ID = EXCLUDED.ALE_ALE_ID,AL_ENTRY_RESOLUTION_WORDING = EXCLUDED.AL_ENTRY_RESOLUTION_WORDING,AL_ENTRY_RESOLUTION_OFFICER = EXCLUDED.AL_ENTRY_RESOLUTION_OFFICER,VERSION = EXCLUDED.VERSION,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,USER_NAME = EXCLUDED.USER_NAME
;





WITH cleaned AS (
SELECT
NCH_ID,
REPLACE(REPLACE(REPLACE(REPLACE(COURTHOUSE_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS COURTHOUSE_NAME,
VERSION_NUMBER,
CHANGED_BY,
CHANGED_DATE,
REPLACE(REPLACE(REPLACE(REPLACE(COURT_TYPE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS COURT_TYPE,
START_DATE,
END_DATE,
LOC_LOC_ID,
PSA_PSA_ID,
REPLACE(REPLACE(REPLACE(REPLACE(COURT_LOCATION_CODE,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS COURT_LOCATION_CODE,
REPLACE(REPLACE(REPLACE(REPLACE(SL_COURTHOUSE_NAME,'\p','|'), '\t',E'\t'), '\r', E'\r'), '\n', E'\n') AS SL_COURTHOUSE_NAME,
NORG_ID
FROM appreg.national_court_houses_temp
),
backslashes_fixed AS (
SELECT
NCH_ID,
REPLACE(COURTHOUSE_NAME,'\\','\') AS COURTHOUSE_NAME,
VERSION_NUMBER,
CHANGED_BY,
CHANGED_DATE,
REPLACE(COURT_TYPE,'\\','\') AS COURT_TYPE,
START_DATE,
END_DATE,
LOC_LOC_ID,
PSA_PSA_ID,
REPLACE(COURT_LOCATION_CODE,'\\','\') AS COURT_LOCATION_CODE,
REPLACE(SL_COURTHOUSE_NAME,'\\','\') AS SL_COURTHOUSE_NAME,
NORG_ID
FROM cleaned
)
INSERT INTO appreg.national_court_houses AS t (
NCH_ID,
COURTHOUSE_NAME,
VERSION_NUMBER,
CHANGED_BY,
CHANGED_DATE,
COURT_TYPE,
START_DATE,
END_DATE,
LOC_LOC_ID,
PSA_PSA_ID,
COURT_LOCATION_CODE,
SL_COURTHOUSE_NAME,
NORG_ID
)
SELECT
NCH_ID,
left(COURTHOUSE_NAME, 100),
VERSION_NUMBER,
CHANGED_BY,
(CHANGED_DATE)::timestamp,
left(COURT_TYPE, 10),
(START_DATE)::timestamp,
NULLIF(END_DATE,'')::timestamp,
LOC_LOC_ID,
PSA_PSA_ID,
NULLIF(left(COURT_LOCATION_CODE, 10),''),
NULLIF(left(SL_COURTHOUSE_NAME, 100),''),
NORG_ID
FROM backslashes_fixed
ON CONFLICT (NCH_ID) DO UPDATE SET
COURTHOUSE_NAME = EXCLUDED.COURTHOUSE_NAME,VERSION_NUMBER = EXCLUDED.VERSION_NUMBER,CHANGED_BY = EXCLUDED.CHANGED_BY,CHANGED_DATE = EXCLUDED.CHANGED_DATE,COURT_TYPE = EXCLUDED.COURT_TYPE,START_DATE = EXCLUDED.START_DATE,END_DATE = EXCLUDED.END_DATE,LOC_LOC_ID = EXCLUDED.LOC_LOC_ID,PSA_PSA_ID = EXCLUDED.PSA_PSA_ID,COURT_LOCATION_CODE = EXCLUDED.COURT_LOCATION_CODE,SL_COURTHOUSE_NAME = EXCLUDED.SL_COURTHOUSE_NAME,NORG_ID = EXCLUDED.NORG_ID
;


DROP SEQUENCE IF EXISTS appreg.AC_SEQ;
CREATE SEQUENCE appreg.AC_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 2622 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.ALEFS_SEQ;
CREATE SEQUENCE appreg.ALEFS_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 4651971 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.ALEO_SEQ;
CREATE SEQUENCE appreg.ALEO_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 5821495 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.ALER_SEQ;
CREATE SEQUENCE appreg.ALER_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 2801856 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.AL_SEQ;
CREATE SEQUENCE appreg.AL_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 3295803 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.AR_SEQ;
CREATE SEQUENCE appreg.AR_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 182669 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.CJA_SEQ;
CREATE SEQUENCE appreg.CJA_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 61 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.FEE_SEQ;
CREATE SEQUENCE appreg.FEE_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 281 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.NA_SEQ;
CREATE SEQUENCE appreg.NA_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 3063188 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.RC_SEQ;
CREATE SEQUENCE appreg.RC_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 221 CACHE 20;
DROP SEQUENCE IF EXISTS appreg.SA_SEQ;
CREATE SEQUENCE appreg.SA_SEQ INCREMENT 1 MINVALUE 1 NO MAXVALUE START 9923 CACHE 20;


update appreg.application_lists set duration_hour = 0 where duration_hour is null;
update appreg.application_lists set duration_minute = 0 where duration_minute is null;
delete from appreg.national_court_houses where court_type <> 'CHOA';

  update appreg.resolution_codes set resolution_code_wording = replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(resolution_code_wording,'TEXTp','TEXT|')
  ,'p75}','|75}')
  ,'p10}','|10}')
  ,'p100}','|100}')
  ,'p3}','|3}')
  ,'p400}','|400}')
  ,'p4}','|4}')
  ,'p5}','|5}')
  ,'p500}','|500}');

    update appreg.application_codes
  set application_code_wording  =   replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(
  replace(application_code_wording,'TEXTp','TEXT|')
  ,'p4}','|4}')
  ,'p3}','|3}')
  ,'p100}','|100}')
  ,'p200}','|200}')
  ,'p70}','|70}')
  ,'p15}','|15}')
  ,'p10}','|10}')
  ,'TXTp','TXT|')
  ,'DATEp','DATE|')
  ,'CURp','CUR|')
  ,'DTp','DT|')
  ,'p80}','|80}')
  ,'p250}','|250}')
  ,'p120}','|120}')
  ,'p150}','|150}')
  ,'p500}','|500}')
  ,'p200','|200')
  ,'sp3}','s|3}');
